site_name: KnowledgeBase
site_description: 'Wissenverzeichnis zu diversen Dingen der Computerei'
site_author: 'Felix Körner'
copyright: 'Copyright &copy; Felix Körner under CC BY-SA 3.0 DE'

# Navigation
nav:
    - Home: 'index.md'
    - IT Security:
        - Hacking the art of exploitation: 'hacking.md'
        - Protostar: 'Protostar.md'
        - OSCP: 'oscp.md'
    - Linux:
        - P2P Network: 'p2p_network.md'
        - RAID Debian: 'raid.md'
    - Test:
        - JDownloader 2.0: 'jd.md'

# Theme
theme: 
        name: material
        palette:
                primary: 'blue'
                accent: 'cyan'
        logo: 'images/logo2.png'
        language: 'en'

#Extensions
markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - codehilite:
        guess_lang: true
        linenums: true
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: false

