site_name: KnowledgeBase
site_description: 'Knowledge directory to various things of computer science'
site_author: 'Felix Körner'
copyright: 'Copyright &copy; Felix Körner under CC BY-SA 3.0 DE'

# Navigation
nav:
    - Home: 'index.md'
    - IT Security:
        - Hacking the art of exploitation: 'hacking.md'
        - Protostar: 'Protostar.md'
        - OSCP: 'oscp.md'
    - Linux:
        - Useful Commands: 'bash.md'
        - P2P Network: 'p2p_network.md'
        - RAID Debian: 'raid.md'
        - Systemd: 'systemd.md'
    - Windows:
        - Borg Backup: 'borg_windows.md'
    - Raspberry Pi:
        - enable ssh: 'raspberrypi_enable_ssh.md'
    - Latex:
        - Digital Signature: 'latex_signature.md'
    - Zoom: 'zoom.md'

# Theme
theme: 
        name: material
        palette:
                primary: 'blue'
                accent: 'cyan'
        logo: 'images/final_250.png'
        language: 'en'
        favicon: 'images/final_favicon.png'
        font: Lato

#Extensions
markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: false
    - pymdownx.tabbed
extra_css:
  - stylesheets/extra.css
