name: Publish MkDocs Material
on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install \
          mkdocs-material \
          pymdown-extensions
      - run: mkdocs gh-deploy --force
  
publish:
  runs-on: ubuntu-latest
  steps:
  - run: echo "Publish Action started"
  - name: Create file
    run: |
      printf "Hello\nWorld\n" > hw.txt

  - name: Create file
    run: |
      echo First        > other.txt
      echo Second Line >> other.txt
      echo Third       >> other.txt


  - name: Show file content
    run: |
      pwd
      ls -la
      cat hw.txt
      cat other.txt


  - name: Create directory and create file in homedir
    run: |
      ls -la ~/
      mkdir ~/.zorg
      echo First        > ~/.zorg/home.txt
      echo Second Line >> ~/.zorg/home.txt
      echo Third       >> ~/.zorg/home.txt
      ls -la ~/.zorg/

  - name: Show file content
    run: |
      ls -la ~/
      cat ~/.zorg/home.txt
